[package]
name = "agave_os"
version = "0.1.0"
edition = "2021"
default-run = "agave_os"

[workspace]
members = ["crates/*", "libs/*"]

[features]
default = ["video", "x86_64"]
x86_64 = []
video = []
serial = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = { version = "0.9.23", features = ["map_physical_memory"] }
agave-kernel = { path = "crates/kernel", features = ["x86_64", "video"] }

[package.metadata.bootimage]
test-success-exit-code = 33 # (0x10 << 1) | 1
