cargo-features = ["per-package-target"]

[package]
name = "agave-kernel"
version = "0.1.0"
edition = "2021"
default-target = "x86_64-unknown-none"

[[bin]]
name = "agave-kernel"
test = false
bench = false

[dependencies]
bootloader_api = "0.11.2"
uart_16550 = "0.2.10"
agave-api = { path = "../api" }
noto-sans-mono-bitmap = { version = "0.1.2", default_features = false, features = ["regular", "size_14"] }
