[package]
name = "agave-kernel"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "agave-kernel"
test = false
bench = false

[features]
default = ["video", "x86_64"]
x86_64 = ["dep:x86_64"]
video = []
serial = []

[dependencies]
bootloader_api = "0.11.2"
x86_64 = { version = "0.14.10", optional = true }
bootloader-x86_64-common = "0.11.3"
conquer-once = { version = "0.4.0", default-features = false }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
log = { version = "0.4.17", default-features = false }
agave-api = { path = "../api" }