[package]
name = "wast-thing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.19"
wasmtime = { path = "../wasmtime", version = "0.1.0", default-features = false, features = [
    'cranelift',
] }
wast = "60.0.0"

