[package]
name = "agave-bootloader-api"
version = "0.1.0"
edition = "2021"

[features]
default = ["video", "x86_64"]
x86_64 = []
video = []
serial = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
acpi = "4.1.0"
